### ISSUE TITLE
Preserve Scroll Position of Background view

### ISSUE THREAD

**Issue by nfunwigabga** [serkodev/nuxt-pages-plus#6]
Nice package...much needed feature.

Is there any way to preserve the scroll position of the background view?

**Comment by serkodev** [comment]
Thank you. It should preserves the scroll position of the background view by default.
Please provide a minimal production if you are having problem on this.

**Comment by nfunwigabga** [comment]
You're right. I created a new app and the scroll position is indeed preserved. There's something wrong with my original implementation...perhaps not related to this package.

**Comment by iambvterrcvp** [comment]
Hi @nfunwigabga , I'm having the same issue., care to share what you did to solve it?

**Comment by develth** [comment]
How did you solved it?
With nuxt4 it always scrolls to top when using `<PlusModalLink>`
Thanks!

**Comment by marco-land** [comment]
> How did you solved it? With nuxt4 it always scrolls to top when using `<PlusModalLink>` Thanks!

I am experiencing the same, did you solve it?

**Comment by develth** [comment]
currently i use on pages that i use with modals the following:

`definePageMeta({ scrollToTop: false })`
